apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ (index .Values.containers 0).name }}
  labels:
    app: {{ .Values.selector.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app }}
    spec:
      containers:
      - name: {{ (index .Values.containers 0).name }}
        image: "{{ (index .Values.images 0).image.repository }}:{{ (index .Values.images 0).image.tag }}"
        imagePullPolicy: {{ (index .Values.images 0).image.pullPolicy }}          
        ports:
          - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      - name: {{ (index .Values.containers 1).name }}
        image: "{{ (index .Values.images 1).image.repository }}:{{ (index .Values.images 1).image.tag }}"
        imagePullPolicy: {{ (index .Values.images 1).image.pullPolicy }}          
        ports:
        - containerPort: 7007
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
      - name: workshopregcred
        