apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: docker-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker_workshop_app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: docker_workshop_app
    spec:          
      containers:
      - name: docker-workshop
        image: workshopregistry.azurecr.io/dockerworkshopapp:v2.5.1
        ports:
        - containerPort: 7005        
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      - name: another-docker-workshop
        image: workshopregistry.azurecr.io/anotherdockerworkshopapp:v2.1.7
        ports:
        - containerPort: 7007
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
      imagePullSecrets:
      - name: workshopregcred
---
apiVersion: v1
kind: Service
metadata:
  name: docker-workshop
spec:
  type: NodePort
  ports:  
  - port: 7005
  selector:
    app: docker_workshop_app


