apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: docker-workshop
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: docker_workshop_app
    spec:      
      containers:      
      - name: docker-workshop
        image: workshopregistry.azurecr.io/dockerworkshopapp:v2.3.5
        ports:
        - containerPort: 7005
        resources:
          requests:
            cpu: "0.25"
          limits:
            cpu: "0.25"
            memory: "50M"      
      imagePullSecrets:
      - name: workshopaksregcred

---
apiVersion: v1
kind: Service
metadata:
  name: docker-workshop
spec:
  type: LoadBalancer
  ports:  
  - port: 7005
  selector:
    app: docker_workshop_app

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: another-docker-workshop
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: another_docker_workshop_app
    spec:      
      containers:      
      - name: another-docker-workshop
        image: workshopregistry.azurecr.io/anotherdockerworkshopapp:v2.1.4
        ports:
        - containerPort: 7007
        resources:
          requests:
            cpu: "0.25"
          limits:
            cpu: "0.25"
            memory: "50M"
      imagePullSecrets:
      - name: workshopaksregcred

---
apiVersion: v1
kind: Service
metadata:
  name: another-docker-workshop
spec:
  type: LoadBalancer
  ports:  
  - port: 7007    
  selector:
    app: another_docker_workshop_app



